/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudyRouteImport } from './routes/study'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyAlRouteImport } from './routes/study.al'
import { Route as InteractivePaperIdRouteImport } from './routes/interactive.$paperId'
import { Route as StudyAlStreamRouteImport } from './routes/study.al.$stream'
import { Route as StudyAlStreamSubjectRouteImport } from './routes/study.al.$stream.$subject'
import { Route as StudyAlStreamSubjectPastPapersRouteImport } from './routes/study.al.$stream.$subject.past-papers'

const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAlRoute = StudyAlRouteImport.update({
  id: '/al',
  path: '/al',
  getParentRoute: () => StudyRoute,
} as any)
const InteractivePaperIdRoute = InteractivePaperIdRouteImport.update({
  id: '/interactive/$paperId',
  path: '/interactive/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyAlStreamRoute = StudyAlStreamRouteImport.update({
  id: '/$stream',
  path: '/$stream',
  getParentRoute: () => StudyAlRoute,
} as any)
const StudyAlStreamSubjectRoute = StudyAlStreamSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => StudyAlStreamRoute,
} as any)
const StudyAlStreamSubjectPastPapersRoute =
  StudyAlStreamSubjectPastPapersRouteImport.update({
    id: '/past-papers',
    path: '/past-papers',
    getParentRoute: () => StudyAlStreamSubjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/study': typeof StudyRouteWithChildren
  '/interactive/$paperId': typeof InteractivePaperIdRoute
  '/study/al': typeof StudyAlRouteWithChildren
  '/study/al/$stream': typeof StudyAlStreamRouteWithChildren
  '/study/al/$stream/$subject': typeof StudyAlStreamSubjectRouteWithChildren
  '/study/al/$stream/$subject/past-papers': typeof StudyAlStreamSubjectPastPapersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/study': typeof StudyRouteWithChildren
  '/interactive/$paperId': typeof InteractivePaperIdRoute
  '/study/al': typeof StudyAlRouteWithChildren
  '/study/al/$stream': typeof StudyAlStreamRouteWithChildren
  '/study/al/$stream/$subject': typeof StudyAlStreamSubjectRouteWithChildren
  '/study/al/$stream/$subject/past-papers': typeof StudyAlStreamSubjectPastPapersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/study': typeof StudyRouteWithChildren
  '/interactive/$paperId': typeof InteractivePaperIdRoute
  '/study/al': typeof StudyAlRouteWithChildren
  '/study/al/$stream': typeof StudyAlStreamRouteWithChildren
  '/study/al/$stream/$subject': typeof StudyAlStreamSubjectRouteWithChildren
  '/study/al/$stream/$subject/past-papers': typeof StudyAlStreamSubjectPastPapersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/contact'
    | '/profile'
    | '/study'
    | '/interactive/$paperId'
    | '/study/al'
    | '/study/al/$stream'
    | '/study/al/$stream/$subject'
    | '/study/al/$stream/$subject/past-papers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/contact'
    | '/profile'
    | '/study'
    | '/interactive/$paperId'
    | '/study/al'
    | '/study/al/$stream'
    | '/study/al/$stream/$subject'
    | '/study/al/$stream/$subject/past-papers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookmarks'
    | '/contact'
    | '/profile'
    | '/study'
    | '/interactive/$paperId'
    | '/study/al'
    | '/study/al/$stream'
    | '/study/al/$stream/$subject'
    | '/study/al/$stream/$subject/past-papers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  ContactRoute: typeof ContactRoute
  ProfileRoute: typeof ProfileRoute
  StudyRoute: typeof StudyRouteWithChildren
  InteractivePaperIdRoute: typeof InteractivePaperIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/al': {
      id: '/study/al'
      path: '/al'
      fullPath: '/study/al'
      preLoaderRoute: typeof StudyAlRouteImport
      parentRoute: typeof StudyRoute
    }
    '/interactive/$paperId': {
      id: '/interactive/$paperId'
      path: '/interactive/$paperId'
      fullPath: '/interactive/$paperId'
      preLoaderRoute: typeof InteractivePaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/al/$stream': {
      id: '/study/al/$stream'
      path: '/$stream'
      fullPath: '/study/al/$stream'
      preLoaderRoute: typeof StudyAlStreamRouteImport
      parentRoute: typeof StudyAlRoute
    }
    '/study/al/$stream/$subject': {
      id: '/study/al/$stream/$subject'
      path: '/$subject'
      fullPath: '/study/al/$stream/$subject'
      preLoaderRoute: typeof StudyAlStreamSubjectRouteImport
      parentRoute: typeof StudyAlStreamRoute
    }
    '/study/al/$stream/$subject/past-papers': {
      id: '/study/al/$stream/$subject/past-papers'
      path: '/past-papers'
      fullPath: '/study/al/$stream/$subject/past-papers'
      preLoaderRoute: typeof StudyAlStreamSubjectPastPapersRouteImport
      parentRoute: typeof StudyAlStreamSubjectRoute
    }
  }
}

interface StudyAlStreamSubjectRouteChildren {
  StudyAlStreamSubjectPastPapersRoute: typeof StudyAlStreamSubjectPastPapersRoute
}

const StudyAlStreamSubjectRouteChildren: StudyAlStreamSubjectRouteChildren = {
  StudyAlStreamSubjectPastPapersRoute: StudyAlStreamSubjectPastPapersRoute,
}

const StudyAlStreamSubjectRouteWithChildren =
  StudyAlStreamSubjectRoute._addFileChildren(StudyAlStreamSubjectRouteChildren)

interface StudyAlStreamRouteChildren {
  StudyAlStreamSubjectRoute: typeof StudyAlStreamSubjectRouteWithChildren
}

const StudyAlStreamRouteChildren: StudyAlStreamRouteChildren = {
  StudyAlStreamSubjectRoute: StudyAlStreamSubjectRouteWithChildren,
}

const StudyAlStreamRouteWithChildren = StudyAlStreamRoute._addFileChildren(
  StudyAlStreamRouteChildren,
)

interface StudyAlRouteChildren {
  StudyAlStreamRoute: typeof StudyAlStreamRouteWithChildren
}

const StudyAlRouteChildren: StudyAlRouteChildren = {
  StudyAlStreamRoute: StudyAlStreamRouteWithChildren,
}

const StudyAlRouteWithChildren =
  StudyAlRoute._addFileChildren(StudyAlRouteChildren)

interface StudyRouteChildren {
  StudyAlRoute: typeof StudyAlRouteWithChildren
}

const StudyRouteChildren: StudyRouteChildren = {
  StudyAlRoute: StudyAlRouteWithChildren,
}

const StudyRouteWithChildren = StudyRoute._addFileChildren(StudyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  ContactRoute: ContactRoute,
  ProfileRoute: ProfileRoute,
  StudyRoute: StudyRouteWithChildren,
  InteractivePaperIdRoute: InteractivePaperIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
